### ISSUE TITLE
Simplified Mixed HMC code does not seem to be working

### ISSUE THREAD

**Issue by JGameCreation** [StannisZhou/mahmc#1]
Hi, I tried your code for simplified Mixed HMC multiple times and I always get all the samples limited to just one of the four modes like this:
![image](https://user-images.githubusercontent.com/11242339/156636051-6148f2fe-97f4-4b7f-bb56-b6c3c4d5b72b.png)
This is not the expected behavior, right?

**Comment by StannisZhou** [comment]
I just tried cloning the repo and running the script. It is working as expected on my side. See the attached figure.

It's a simple script with minimal dependencies and I'm surprised it would give inconsistent results....I'm running with python 3.8.12, numpy 1.20.3 and numba 0.54.1. Not sure if it's related to package versions. Could you share your setup?

![Screenshot from 2022-03-03 11-34-34](https://user-images.githubusercontent.com/10180197/156640678-d32e6d25-6ab1-4d42-9ea2-897012b7d456.png)

**Comment by JGameCreation** [comment]
Hmm, that's strange. I'm using
Python 3.10.2
numpy 1.21.5
numba 0.55.0
Thanks for the super fast reply!

**Comment by JGameCreation** [comment]
I tried running the code on Google Colab and it works so it's definitely a problem with my setup, not with your code.

**Comment by StannisZhou** [comment]
Glad to hear! And if you figure out the issue also let me know
